website/__init__.py
from flask import Flask
from secret_key_generator import secret_key_generator
from os import path
from flask_login import LoginManager

def create_app():
    SECRET_KEY = secret_key_generator.generate()
    app = Flask(__name__)
    app.config['SECRET_KEY'] = SECRET_KEY

    from .views import views
    app.register_blueprint(views, url_prefix="/")

    return app

website/views.py
import threading
import time
from flask import jsonify, Blueprint, render_template, request, flash, session, redirect, url_for
from flask.cli import with_appcontext
import json
from ideasearch import ideasearcher
from concurrent.futures import ThreadPoolExecutor
from ideasearch.utils import query
import json
import requests
from bs4 import BeautifulSoup

views = Blueprint('views', __name__)
executor = ThreadPoolExecutor(2)


def get_search_desc(idea):
    return idea


def get_search_title(idea):
    return idea


def get_meta(search_data):
    tag = search_data[0].data[0]
    url = search_data[0].data[1]
    image = None
    extra_data = []
    if tag == 'GOOGLE_WEBSITE' or tag == 'YOUTUBE':
        info = extract_info(url, tag)
        if info == -1:
            image = find_icon(tag)
        else:
            image = info['image_url']
        extra_data = [url]

    elif tag == 'SCHOLAR':
        extra_data = [f'Paper Link : {search_data[0].data[1]}', f'Paper ID : {search_data[0].data[2]}']
        image = find_icon(tag)
        url = ''
    elif tag == 'PATENT':
        extra_data = [f'Patent Number : {search_data[0].data[1]}', f'Patent Date : {search_data[0].data[2]}']
        image = find_icon(tag)
        url = ''

    return image, extra_data, url



def find_icon(tag):
    if tag == 'PATENT':
        return url_for('static', filename='images/PatentIcon2.svg')
    elif tag == 'GOOGLE_WEBSITE':
        return url_for('static', filename='images/GoogleIcon.svg')
    elif tag == 'YOUTUBE':
        return url_for('static', filename='images/YoutubeIcon1.svg')
    elif tag == 'SCHOLAR':
        return url_for('static', filename='images/ScholarIcon.svg')


def execute_heavy_job(search_depth):
    global future

    idea = session.get('idea')

    future = executor.submit(ideasearcher.search_idea, idea, 0.25, 2, search_depth)
    future.add_done_callback(custom_callback)
    return 'Heavy job started. Result will be available soon.'


@views.route('/idea', methods=['GET', 'POST'])
def idea():
    if request.method == 'POST':
        index = request.form.get('index')
        current_res = future.result()[int(index)]

        image_l, extra_d, url = get_meta(current_res)
        type = current_res[0].data[0]
        return render_template('idea3.html', result=current_res, icon=find_icon(type), image_link=image_l, extra_data=extra_d, url=url)
    return "<h1>Hello</h1>"


@views.route('/check_job')
def check_job():
    if future.done():
        return 'completed'
    else:
        return 'running'


@views.route('/', methods=['GET', 'POST'])
def home():
    if request.method == 'POST':
        idea = request.form.get('idea')
        search_depth = False
        if request.form.get('search_depth') == 'on':
            search_depth = True
        else:
            search_depth = False

        session['idea'] = idea

        execute_heavy_job(search_depth)

        # Thread return progress through return of the function
        return redirect(url_for('views.loading'))

    return render_template('home.html')


@views.route('/loading')
def loading():
    return render_template('loading.html')


@views.route('/results', methods=['GET', 'POST'])
def results():
    if future.done():
        r = future.result()
        # session['results'] = jsonify(r)
        '''
        sum = 0
        for i in range(len(r)):
            sum += (1 - r[i][1]) * 100
        s = round(sum / len(r), 2)
        '''
        s = round(1 - r[0][1], 2) * 100
        return render_template('results.html', score=s, result=r, find_icon=find_icon, result_range=range(len(r)))
    else:
        return "The heavy job is still running. Please wait."


def custom_callback(fn):
    if fn.cancelled():
        print(f'{fn.arg}: canceled')
        return 'canceled'
    elif fn.done():
        error = fn.exception()
        if error:
            print(f'task: error returned: {error}')
            fn.result()
            return 'error'
        else:
            result = fn.result()

            print(f'task - {result} is done')
            return 'completed'
    return 'running'


def extract_info(url, tag):
    try:
        response = requests.get(url)
        soup = BeautifulSoup(response.text, 'html.parser')

        default_image_url = find_icon(tag)

        # Extract title, description, and preview image
        title = soup.find('title').text
        description = soup.find('meta', {'name': 'description'})['content']

        # Check if the webpage has Open Graph metadata
        og_image = soup.find('meta', {'property': 'og:image'})
        if og_image:
            image_url = og_image['content']
        else:
            # If no Open Graph metadata is found, assign the default image URL
            image_url = default_image_url

        return {'url': url, 'title': title, 'description': description, 'image_url': image_url}
    except Exception as e:
        print('ERROR', e)
        return -1

website/templates/home.html
<!DOCTYPE html>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://fonts.googleapis.com/css?family=Quicksand' rel='stylesheet'>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.14.0/js/bootstrap-select.min.js"></script>
    <title>The Deep End</title>
    <style>




        * {
  box-sizing: border-box;
}
body {
  margin: 0;
}
#im73{
  background-repeat:repeat;
  background-position:left top;
  background-attachment:scroll;
  background-size:auto;
  background-image:linear-gradient(#f2f2f2 0%, #f2f2f2 100%);
}
.gjs-row{
  display:flex;
  justify-content:flex-start;
  align-items:stretch;
  flex-wrap:nowrap;
  padding:10px;
}
.gjs-cell{
  min-height:75px;
  flex-grow:1;
  flex-basis:100%;
}
#ikwzb{
  flex-basis:35%;
}
#i1t7p{
  flex-basis:47%;
}
@media (max-width: 768px){
  .gjs-row{
    flex-wrap:wrap;
  }
}

        body {
           font-family: 'Quicksand';
           font-size:40px;
           background : white;
        }
        label{
           font-family: 'Quicksand';
           font-size:40px;
        }
        submit{
          background-color: #04AA6D;
          border: none;
          color: white;
          padding: 16px 32px;
          text-decoration: none;
          margin: 4px 2px;
          cursor: pointer;
        }

        dropdown-checkboxes{

            width:200px;
            height:100px;

        }

        .switch {
          position: relative;
          display: inline-block;
          width: 60px;
          height: 34px;
        }

        /* Hide default HTML checkbox */
        .switch input {
          opacity: 0;
          width: 0;
          height: 0;
        }

        /* The slider */
        .slider {
          position: absolute;
          cursor: pointer;
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
          background-color: #ccc;
          -webkit-transition: .4s;
          transition: .4s;
        }

        .slider:before {
          position: absolute;
          content: "";
          height: 26px;
          width: 26px;
          left: 4px;
          bottom: 4px;
          background-color: white;
          -webkit-transition: .4s;
          transition: .4s;
        }

        input:checked + .slider {
          background-color: #2196F3;
        }

        input:focus + .slider {
          box-shadow: 0 0 1px #2196F3;
        }

        input:checked + .slider:before {
          -webkit-transform: translateX(26px);
          -ms-transform: translateX(26px);
          transform: translateX(26px);
        }

        /* Rounded sliders */
        .slider.round {
          border-radius: 34px;
        }

        .slider.round:before {
          border-radius: 50%;
        }

    </style>

</head>


<body id="im73">

  <div class="gjs-row" id="iym8">
    <div class="gjs-cell">
    </div>
    <div class="gjs-cell" id="i30t">
        <img src="{{ url_for('static', filename='images/logo3.svg') }}" alt="Welcome to Idea-Search.com!" width="1000"
        height="250" style="display: block; margin: 0 auto;">
    </div>
    <div class="gjs-cell">
    </div>
  </div>

  <div class="gjs-row" id="ijhbr">
    <div class="gjs-cell" id="i1t7p">
    </div>
    <div class="gjs-cell">
         <p1 style="font-size:40px;font-size:50px;font-family:'Quicksand';">Explore the possibilities: validate your idea or uncover similar ideas!</p1>
    </div>
    <div class="gjs-cell" id="ikwzb">
    </div>
  </div>

  <div class="gjs-row" id="ip98h">
    <div class="gjs-cell">
    </div>
<div class="gjs-cell">
  <form method="POST" style="display: flex; align-items: center;">
    <label for="idea" style="font-size: 25px; font-family: Quicksand;"></label><br>
    <input style="height: 3vw; font-family: Quicksand; width: 50vw; color: black; font-size: 30px; font-family: Quicksand; text-align: center; padding-right: 10px; margin-right: -10px;"
           type="text" id="idea" name="idea" placeholder="Tell me about your idea...">

    <input style="height: 3vw; font-family: Quicksand; font-size: 25px; background-color: white; color: grey; padding: 16px 32px; text-decoration: none; cursor: pointer; text-align: center; display: flex; align-items: center; justify-content: center;"
           type="submit" value="Discover">
  </form>
</div>
    <div class="gjs-cell">
        <label class="switch" for="search_depth" style="margin-left:10px">
            <input type="checkbox" id="search_depth" name="search_depth">
            <span class="slider round"></span>
        </label>
    </div>
  </div>


</body>

</html>

website/templates/idea.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Idea Data</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <style>

        .text{
            width=50vw;
        }


      * {
  box-sizing: border-box;
}

body {
  font-family: Arial, Helvetica, sans-serif;
}

/* Style the header */
header {
  background-color: #766;
  padding: 30px;
  text-align: left;
  font-size: 20px;
  color: white;
  width:60%;
}


article {
  float: left;
  padding: 20px;
  width: 60%;
  background-color: #f1f1f1;
  font-size: 20px;
}

gallery{
    float:right

}

/* Clear floats after the columns */
section::after {
  content: "";
  display: table;
  clear: both;
}

footer {

  background-color: white;
  color: black;
}

/* Responsive layout - makes the two columns/boxes stack on top of each other instead of next to each other, on small screens */
@media (max-width: 600px) {
  nav, article {
    width: 100%;
    height: auto;
  }
}

@property --progress-value {
    syntax: "<integer>";
    initial-value: 0;
    inherits: false;
  }

  @keyframes progress {
    to { --progress-value: var(--current-value, 0); }
  }

  .progress-bar {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 120px;
    height: 120px;
    border-radius: 50%;
    background:
      radial-gradient(closest-side, white 79%, transparent 80% 100%),
      conic-gradient(blue calc(var(--progress-value) * 1%), lightblue 0);
    animation: progress 2s 1 forwards;
  }

  .progress-bar::before {
    counter-reset: percentage var(--progress-value);
    content: counter(percentage) '%';
    animation: progress 2s 1 forwards;
  }


    </style>
</head>
<body>

<header>
   <h1 class="text">Idea Title : </h1>
    <h2 class="text">{{ result[0].title }}</h2>
</header>

<h1> Similar </h1>
        <div class="progress-bar">
            <progress id="progress" value="75" min="0" max="100" style="visibility:hidden;height:0;width:0;"></progress>
        </div>

        <script>
        const progressElement = document.getElementById('progress');
        const progressValue = progressElement.value;
        const currentStyle = getComputedStyle(document.documentElement);
        document.documentElement.style.setProperty('--current-value', Math.round({{ result[1]*100 }}));

        </script>

<section>

  <article>
    {% if ( result[0].description != None or  result[0].description != "NA") %}
        <h1 class="text"> Idea Description : </h1>
       <h3 class="text" > {{  result[0].description  }}</h3>
    {% endif %}
  </article>
    <gallery>
        <img title= "{{result[0].data[0]}}" style="width:300px;height:300px;" src="{{ find_icon(result[0].data[0])}}">

    </gallery>
</section>


<footer>


    <h1 class="text" >Meta Data : </h1>

    <a href="{{ url }}">
        <img src="{{ image_link }}" alt="preview" style="width:40vw;height:20vw;">
        <h3 style="width:40vw;">Link : {{ url }}</h3>
    </a>

    {% for ed in extra_data %}
    <h3>{{ ed }} </h3>
    {% endfor %}


</footer>




<button type="button" class="close" onClick="window.location.href = '/results';"
                    style="background-color:navy;border: none;color: white;padding: 16px 32px;text-decoration: none;margin: 4px 2px;cursor: pointer;">
                Back to Results Page
            </button>

</body>
</html>

website/templates/idea2.html
<!DOCTYPE html>
<html lang="en">
<head>

    <script>
function populateDescriptionBox(text) {
  var descriptionBox = document.getElementById('description-box');
  var description = document.getElementById('description');

  description.innerText = text;

  descriptionBox.style.height = 'auto'; // Reset the height to recalculate

  if (description.scrollHeight <= descriptionBox.clientHeight) {
    // Text does not overflow
    description.style.fontSize = '16px'; // Reset font size if previously resized
    descriptionBox.style.height = description.scrollHeight + 'px';
  } else {
    // Text overflows
    description.style.fontSize = '12px'; // Decrease font size
    descriptionBox.style.height = descriptionBox.clientHeight + 'px';
  }
}




    </script>
    <style>
description-box {
  max-height: 20vw;
  overflow: auto;
}

description {
  width: 100%;
  box-sizing: border-box;
  font-size: 16px;
}
        * {
  box-sizing: border-box;
}
body {
  margin: 0;
}
.gjs-row{
  display:flex;
  justify-content:flex-start;
  align-items:stretch;
  flex-wrap:nowrap;
  padding:10px;
}
.gjs-cell{
  min-height:75px;
  flex-grow:1;
  flex-basis:100%;
}
#i8hg{
  height:659px;
}
#i492{
  height:171px;
}
#ivdt{
  height:182px;
}
#if4u9{
  height:191px;
}
#ihyu8{
  height:315px;
}
#iv3z1{
  height:325px;
}
@media (max-width: 768px){
  .gjs-row{
    flex-wrap:wrap;
  }
}
        .text{
            width=50vw;
        }


      * {
  box-sizing: border-box;
}

body {
  font-family: Arial, Helvetica, sans-serif;
}

/* Style the header */
header {
  background-color: #766;
  padding: 30px;
  text-align: left;
  font-size: 20px;
  color: white;
  width:60%;
}


article {
  float: left;
  padding: 20px;
  width: 60%;
  font-size: 20px;
}

gallery{
    float:right

}

/* Clear floats after the columns */
section::after {
  content: "";
  display: table;
  clear: both;
}

footer {

  background-color: white;
  color: black;
}

/* Responsive layout - makes the two columns/boxes stack on top of each other instead of next to each other, on small screens */
@media (max-width: 600px) {
  nav, article {
    width: 100%;
    height: auto;
  }
}

@property --progress-value {
    syntax: "<integer>";
    initial-value: 0;
    inherits: false;
  }

  @keyframes progress {
    to { --progress-value: var(--current-value, 0); }
  }

  .progress-bar {
    display: flex;
    justify-content: center;
    align-items: center;

    width: 20vw;
    margin-left:12vw;
    height: 20vw;
    border-radius: 50%;
    background:
      radial-gradient(closest-side, white 79%, transparent 80% 100%),
      conic-gradient(blue calc(var(--progress-value) * 1%), lightblue 0);
    animation: progress 2s 1 forwards;
  }

  .progress-bar::before {
    counter-reset: percentage var(--progress-value);
    content: counter(percentage) '%';
    animation: progress 2s 1 forwards;
  }











    </style>
</head>
<body id="im73">

  <div id="i8hg" class="gjs-row">
    <div id="ilo9" class="gjs-cell">
      <div id="i12s" class="gjs-row">
        <div class="gjs-cell">
            <h1 class="text">Idea Title : </h1>
            <h2 class="text">{{ result[0].title }}</h2>
        </div>
      </div>
      <div id="i492" class="gjs-row">
        <div class="gjs-cell">
        </div>
      </div>
      <div id="ivdt" class="gjs-row">
        <div id="ipr3" class="gjs-cell">
        </div>
      </div>
      <div id="if4u9" class="gjs-row">
        <div id="ipt03" class="gjs-cell">
        </div>
      </div>
    </div>
    <div id="i4og" class="gjs-cell">
      <div id="ihyu8" class="gjs-row">
        <div id="iq1z9" class="gjs-cell">
        </div>
      </div>
      <div id="iv3z1" class="gjs-row">
        <div class="gjs-cell">
        </div>
      </div>
    </div>
  </div>


<div class="gjs-row" id="i8hg">
    <div class="gjs-cell" id="ilo9">
        <div class="gjs-row" id="i12s">
            <div class="gjs-cell">

            </div>
        </div>
        {% if result[0].data[0] == 'YOUTUBE'%}
        <div class="gjs-row" id="i492">

            <div class="gjs-cell">
                <a href="{{ url }}">
                    <img src="{{ image_link }}" alt="preview" style="width:40vw;height:20vw;">
                    <h3 style="width:40vw;">Link : {{ url }}</h3>
                </a>
            </div>
        </div>
        {% endif %}

        <div class="gjs-row" id="ivdt">
            {% if ( result[0].description != None or result[0].description != "NA") %}
            <div class="gjs-cell" id="ipr3">

                <h1 class="text"> Idea Description : </h1>
                <div id="description-box">
                    <div id="description">

                        <h1 class="text"> {{ result[0].description }}</h1>
                    </div>
                </div>

            </div>
        </div>
        {% endif %}
    </div>
</div>

<div class="gjs-row" id="if4u9">
    <div class="gjs-cell" id="ipt03">
        <footer>


            <h1 class="text">Links : </h1>

            {% for ed in extra_data %}
            <h3>{{ ed }} </h3>
            {% endfor %}


        </footer>
    </div>
</div>
</div>

<div class="gjs-cell" id="i4og">
    <div class="gjs-row" id="ihyu8">
        <div class="gjs-cell" id="iq1z9">
            <div class="progress-bar">
                <progress id="progress" value="75" min="0" max="100"
                          style="visibility:hidden;height:0;width:0;"></progress>
            </div>

            <script>
        const progressElement = document.getElementById('progress');
        const progressValue = progressElement.value;
        const currentStyle = getComputedStyle(document.documentElement);
        document.documentElement.style.setProperty('--current-value', Math.round({{ result[1]*100 }}));





            </script>
        </div>
    </div>
    <div class="gjs-row" id="iv3z1">
        <div class="gjs-cell" id="ind0n">
            <img src="{{ find_icon(result[0].data[0]) }}" alt="Type" style="height:20vw;width:20vw;">
        </div>
    </div>
</div>
</div>
</body>
</html>

website/templates/idea3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Idea Data</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script>
function populateDescriptionBox(text) {
  var descriptionBox = document.getElementById('description-box');
  var description = document.getElementById('description');

  description.innerText = text;

  descriptionBox.style.height = 'auto'; // Reset the height to recalculate

  if (description.scrollHeight <= descriptionBox.clientHeight) {
    // Text does not overflow
    description.style.fontSize = '16px'; // Reset font size if previously resized
    descriptionBox.style.height = description.scrollHeight + 'px';
  } else {
    // Text overflows
    description.style.fontSize = '12px'; // Decrease font size
    descriptionBox.style.height = descriptionBox.clientHeight + 'px';
  }
}










    </script>
    <style>
            .text{
            width=50vw;
        }


      * {
  box-sizing: border-box;
}

body {
  font-family: Arial, Helvetica, sans-serif;
}

/* Style the header */
header {
  background-color: #766;
  padding: 30px;
  text-align: left;
  font-size: 20px;
  color: white;
  width:60%;
}


article {
  float: left;
  padding: 20px;
  width: 60%;
  background-color: #f1f1f1;
  font-size: 20px;
}

gallery{
    float:right

}

/* Clear floats after the columns */
section::after {
  content: "";
  display: table;
  clear: both;
}

footer {

  background-color: white;
  color: black;
}

/* Responsive layout - makes the two columns/boxes stack on top of each other instead of next to each other, on small screens */
@media (max-width: 600px) {
  nav, article {
    width: 100%;
    height: auto;
  }
}

@property --progress-value {
    syntax: "<integer>";
    initial-value: 0;
    inherits: false;
  }

  @keyframes progress {
    to { --progress-value: var(--current-value, 0); }
  }

  .progress-bar {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 20vw;
    height: 20vw;
    border-radius: 50%;
    background:
      radial-gradient(closest-side, white 79%, transparent 80% 100%),
      conic-gradient(blue calc(var(--progress-value) * 1%), lightblue 0);
    animation: progress 2s 1 forwards;
  }

  .progress-bar::before {
    counter-reset: percentage var(--progress-value);
    content: counter(percentage) '%';
    animation: progress 2s 1 forwards;
  }

* {
  box-sizing: border-box;
}
body {
  margin: 0;
}
.gjs-row{
  display:flex;
  justify-content:flex-start;
  align-items:stretch;
  flex-wrap:nowrap;
  padding:10px;
}
.gjs-cell{
  min-height:75px;
  flex-grow:1;
  flex-basis:100%;
}
#i8hg{
  height:1000px;
}
#i492{
  height:171px;
}
#ivdt{
  height:182px;
  position:relative;
}
#if4u9{
  height:191px;
  position:relative;
}
#ihyu8{
  height:315px;
  position:fixed;
}
#iv3z1{
  height:325px;
}
#ihdhd{
  position:relative;
}
#i12s{
  position:fixed;
}
#is7ab{
  position:relative;
}
#iqsyu{
  height:315px;
}
#idea_type{
  justify-content:flex-end;
  position:fixed;
}
#similarity{
  justify-content:flex-end;
  position:fixed;
}
@media (max-width: 768px){
  .gjs-row{
    flex-wrap:wrap;
  }
}








    </style>
</head>
<body id="im73">
<div id="i8hg" class="gjs-row">
    <div id="ilo9" class="gjs-cell">
        <div id="i12s" class="gjs-row">
            <div class="gjs-cell" id="iblh">


            </div>
        </div>
        <div id="i492" class="gjs-row">
            <div id="idea_title" title="idea_title" class="gjs-cell">

                <h1 class="text">Idea Title : </h1>
                <h2 class="text">{{ result[0].title }}</h2>

            </div>
        </div>
        {% if result[0].data[0] == 'YOUTUBE'%}

        <div id="ivdt" class="gjs-row">
            <div id="idea_display" title="idea_display" class="gjs-cell">

                <a href="{{ url }}">
                    <img src="{{ image_link }}" alt="preview" style="width:40vw;height:20vw;">
                </a>
            </div>
        </div>

        {% endif %}
        <div id="if4u9" class="gjs-row">
            <div id="idea_desc" title="idea_desc" class="gjs-cell">
                {% if ( result[0].description != None or result[0].description != "NA") %}
                <h1 class="text"> Idea Description : </h1>
                <h3 class="text"> {{ result[0].description }}</h3>
                {% endif %}
            </div>
        </div>
        <div class="gjs-row" id="is7ab">
            <div id="idea_links" title="idea_links" class="gjs-cell">
                {% for ed in extra_data %}
                <h3>{{ ed }} </h3>
                {% endfor %}
            </div>
        </div>
    </div>
    <div id="i4og" class="gjs-cell">
        <div id="ihyu8" class="gjs-row">
            <div id="iq1z9" class="gjs-cell">
                <div id="ihdhd">
                </div>
            </div>
        </div>
        <div id="iv3z1" class="gjs-row">
            <div id="similarity" title="similarity" class="gjs-cell">
                <div class="progress-bar">
                    <progress id="progress" value="75" min="0" max="100"
                              style="visibility:hidden;height:0;width:0;"></progress>
                </div>

                <script>
        const progressElement = document.getElementById('progress');
        const progressValue = progressElement.value;
        const currentStyle = getComputedStyle(document.documentElement);
        document.documentElement.style.setProperty('--current-value', Math.round({{ result[1]*100 }}));


                </script>
            </div>
        </div>
        <div class="gjs-row" id="iqsyu">
            <div id="idea_type" title="idea_type" class="gjs-cell">
                <img title="{{result[0].data[0]}}" style="width:20vw;height:20vw;margin-top:4vw;"
                     src="{{ icon }}">
            </div>


        </div>


    </div>
</div>

<button type="button" class="close" onClick="window.location.href = '/results';"
                    style="background-color:navy;border: none;color: white;padding: 16px 32px;text-decoration: none;margin: 4px 2px;cursor: pointer;">
                Back to Results Page
            </button>
</body>
</html>

website/templates/loading.html
<!DOCTYPE html>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <title>Loading Data</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


    <style>
        .loader{
            position : fixed;
            top : 0;
            left : 0;
            width : 100vw;
            height : 100vh;
            display : flex;
            align-items : center;
            justify-content : center;
            background : #DCDCDC;
            transition: opacity 0.75s, visibility 0.75s ;
        }
        .loader::after{
            content: "";
            width:75px;
            height:75px;
            border:15px solid #dddddd;
            border-top-color: #009578;
            border-radius:50%;
            animation: loading 0.75s ease infinite;


        }

        .loader--hidden{
            opacity:0;
            visibility:hidden;

        }

        @keyframes loading{
            from { transform : rotate(0turn) }
            to { transform : rotate(1turn) }
        }
    </style>
    <!--
    <script>
        window.addEventListener("load", () =>{
            document.querySelector(".loader").classList.add("loader--hidden");
        });
    </script>
    !-->

    <script>

          var heavyJobUrl = '{{ url_for("views.check_job") }}';

          // Periodically check if the heavy job is finished
          var checkJobInterval = setInterval(function() {
              $.ajax({
                  url: heavyJobUrl,
                  success: function(data) {
                      if (data === 'completed') {
                          clearInterval(checkJobInterval);
                          window.location.href = '/results';
                      }
                  }
              });
          }, 5000);  // Adjust the interval as needed
      </script>
</head>
  <body>

  <div class="loader"></div>




</body>
</html>

website/templates/test.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Progress Bar Example</title>
  <style>
  @property --progress-value {
    syntax: "<integer>";
    initial-value: 0;
    inherits: false;
  }

  @keyframes progress {
    to { --progress-value: var(--current-value, 0); }
  }

  .progress-bar {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 100px;
    height: 100px;
    border-radius: 50%;
    background:
      radial-gradient(closest-side, white 79%, transparent 80% 100%),
      conic-gradient(blue calc(var(--progress-value) * 1%), lightblue 0);
    animation: progress 2s 1 forwards;
  }

  .progress-bar::before {
    counter-reset: percentage var(--progress-value);
    content: counter(percentage) '%';
    animation: progress 2s 1 forwards;
  }
  </style>
</head>

<body>
  <div class="progress-bar">
    <progress id="progress" value="75" min="0" max="100" style="visibility:hidden;height:0;width:0;"></progress>
  </div>
  <iframe width="560" height="315"  src="https://www.youtube.com/embed/7TF00hJI78Y" frameborder="0" allowfullscreen></iframe>
  <script>
    const progressElement = document.getElementById('progress');
    const progressValue = progressElement.value;
    const currentStyle = getComputedStyle(document.documentElement);
    document.documentElement.style.setProperty('--current-value', {{ 5 }});
  </script>
</body>
</html>